name: MAIN_PULL_REQUESTS

on:
  pull_request:
    branches: [develop, main, master]
    types: [opened, synchronize, reopened]

jobs:
  MAIN_PULL_REQUEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
      - name: check_email
        run: |
          log_emails=$(git log --pretty=format:"%ae" -1) && if [[ ${log_emails} =~ '@tencent.com' ]];then echo $log_emails && echo "邮箱校验非法" && exit 2;else echo "邮箱校验通过";fi
        shell: bash
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-nodemodules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm install
        shell: bash

      # - run: exit 1;

      - run: |
          zip -r _site.zip _site
      - name: upload _site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site.zip
          retention-days: 5

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt
      - name: update status comment
        uses: actions-cool/maintain-one-comment@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            .... 打包好了
          number: ${{ github.event.number }}
      - run: exit 1;