name: install dep

on:
  workflow_call:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
      - name: check_email
        run: |
          log_emails=$(git log --pretty=format:"%ae" -1) && if [[ ${log_emails} =~ '@tencent.com' ]];then echo $log_emails && echo "邮箱校验非法" && exit 2;else echo "邮箱校验通过";fi
        shell: bash
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: node -v
      - name: Install dependencies
        run: npm install
        shell: bash
      - run: touch a.txt | echo 111 > a.txt